//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronXfmsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsVisualize
    {
        public string QueryID { get; set; }
        public string FastaFileInfo { get; set; }
        public string PeptideInfo { get; set; }
        public string PfSasaTabXlsFile { get; set; }
        public string BridgeResultsFile { get; set; }
        public string SasaMainImageFile { get; set; }
        public string PfModifiedPdb { get; set; }
        public string CentralityModifiedPdb { get; set; }
        public int ID { get; set; }
    }
}
