//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerceptronXfmsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchQuery
    {
        public string QueryID { get; set; }
        public string UserID { get; set; }
        public string Progress { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string isBridgeEnabled { get; set; }
        public string isFrustratometerEnabled { get; set; }
        public string EmailID { get; set; }
        public int ID { get; set; }
    }
}
